version: '3'
services:
  db:
    build: ./wechat-mysql
    restart: always
  koa:
    build: ./wechat-koa
    ports:
     - "80:2333"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  