CREATE TABLE IF NOT EXISTS birthday (
  name VARCHAR(10) NOT NULL PRIMARY KEY,
  lunarDate VARCHAR(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS person {
  bookId INT,
  name VARCHAR(10)
};
CREATE TABLE IF NOT EXISTS types {
  bookId INT,
  type VARCHAR(20)
};
CREATE TABLE IF NOT EXISTS 